[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "click>=8.0.0",
    "colorlog>=6.0.0",
    "packaging>=21.0.0",
    "requests>=2.25.0",
    "stringzilla>=3.12.6",
    "toml>=0.10.0",
]
